apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-management-rolebinding
subjects:
- kind: ServiceAccount
  name: chaos-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-management-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-management-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "deletecollection"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
