name: Build and Push Chaos Experiment Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DNAME }}
        password: ${{ secrets.DPASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: uditgaurav/stress-chaos-test:0.1.0

